name: github checkout

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 다른 레포지토리의 action 사용
      - uses: actions/checkout@v2 # Runner 머신에 레포지토리 클론 및 체크아웃

      - name: Run pwd
        run: pwd

      - name: Run ls -al
        run: ls -al
