name: secrets

on: ['push']
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Print Repository Secrets.TEST_PASSWORD
        run: echo "TEST_PASSWORD => ${{ secrets.TEST_PASSWORD }}"
